### ISSUE TITLE
Cannot connect to gmail account

### ISSUE THREAD

**Issue by marlemion** [owncloud/mail#444]
I pulled master to the apps directory, set the correct user/group, installed the missing dependencies in the mail app folder using composer.phar, changed user/group accordingly, activated the mail app and tried to insert the desired data. Tried both: automatic and manual. Tried both: gmail and googlemail address. No result with the automatic method, 'bad request' result with the manual method.

Settings:  imap.gmail.com, 993, SSL, user=email, password and smtp.gmail.com, 465, SSL, user=email, password

Log:

{"reqId":"b9c79b324f141edc05f12821f5c9e976","remoteAddr":"xxxxx","app":"mail","message":"Setting up manually configured account","level":1,"time":"2015-04-02T08:12:53+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"b9c79b324f141edc05f12821f5c9e976","remoteAddr":"xxxxx","app":"mail","message":"Connecting to imap","level":0,"time":"2015-04-02T08:12:53+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"b9c79b324f141edc05f12821f5c9e976","remoteAddr":"xxxxx","app":"mail","message":"Creating account failed: Error when communicating with the mail server.","level":3,"time":"2015-04-02T08:13:03+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}

**Comment by DeepDiver1975** [comment]
did you enable imap/smtp usage on your gmail account?

https://support.google.com/mail/troubleshooter/1668960?hl=en#ts=1665018

**Comment by marlemion** [comment]
Certainly, I use it since ages without any glitch with kmail.

**Comment by marlemion** [comment]
This might be interesting, too. It is a result from the automatic connection try:

Exception: {"Message":"IMAP error reported by server.","Code":0,"Trace":"#0 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4206): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\n#1 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\n#2 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php(1659): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\n#3 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Base.php(1687): Horde_Imap_Client_Socket->_status(Array, 1)\n#4 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/mailbox.php(125): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\n#5 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/mailbox.php(129): OCA\\Mail\\Mailbox->getStatus(1)\n#6 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php(280): OCA\\Mail\\Mailbox->getTotalMessages()\n#7 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php(189): OCA\\Mail\\Account->getSpecialFolder('drafts', true)\n#8 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php(319): OCA\\Mail\\Account->getSpecialFoldersIds(false)\n#9 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php(135): OCA\\Mail\\Account->localizeSpecialMailboxes()\n#10 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php(147): OCA\\Mail\\Account->getMailboxes()\n#11 \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/controller\/folderscontroller.php(57): OCA\\Mail\\Account->getListArray()\n#12 [internal function]: OCA\\Mail\\Controller\\FoldersController->index()\n#13 \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(158): call_user_func_array(Array, Array)\n#14 \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(86): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#15 \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Mail\\Controller\\FoldersController), 'index')\n#16 \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('FoldersControll...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#17 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#18 \/var\/www\/localhost\/htdocs\/owncloud\/lib\/private\/route\/router.php(250): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#19 \/var\/www\/localhost\/htdocs\/owncloud\/lib\/base.php(767): OC\\Route\\Router->match('\/apps\/mail\/acco...')\n#20 \/var\/www\/localhost\/htdocs\/owncloud\/index.php(36): OC::handleRequest()\n#21 {main}","File":"\/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php","Line":4488}

**Comment by marlemion** [comment]
I have tried various combinations of 'ssl' 'tls' (they seem to be necessarily decapitalized according to the code) and ports (993 for imap, 465, 587 for smtp) as well as server/email names (gmail vs. googlemail). No success. How is this even possible? Thats the first step anybody has to perform to get it running and gmail is more or less one of the standard email services out there. Why do the logs output nothing really helpful telling me where the problem might be? PHP is compiled with SSL support. What else might be missing? Any library? owncloud is at 8.0.2 is functioning very well also with 3rd party plugins.

**Comment by marlemion** [comment]
Ok, get this here in apache error.log:

[Thu Apr 02 16:58:21.994787 2015] [:error] [pid 8703:tid 2949641264] [client XXXXXX:55824] PHP Fatal error:  Call to a member function getId() on string in /var/www/localhost/htdocs/owncloud/apps/mail/lib/controller/accountscontroller.php on line 174, referer: http://XXXXX/owncloud/index.php/apps/mail/

So it is related to https://github.com/owncloud/mail/issues/210

Whats the problem?

**Comment by marlemion** [comment]
When I point my browser to owncloud/index.php/apps/mail/accounts I get the account with the proper settings. However, it does not connect. Anyway, I think I will look for something more useful.

**Comment by marlemion** [comment]
### Steps to reproduce
1. Add gmail account

### Expected behaviour
Should add the account and provide imap access

### Actual behaviour
Throws error:  PHP Fatal error: Call to a member function getId() on string in /var/www/localhost/htdocs/owncloud/apps/mail/lib/controller/accountscontroller.php on line 174

### Server configuration
**Operating system**: Linux 3.8, ARM, Odroid U2, Gentoo

**Web server:** Apache 2.4.12

**Database:** mysql 5.6.23

**PHP version:** 5.6.7

**ownCloud version:** 8.0.2 (latest stable)

**Updated from an older ownCloud or fresh install:** Updated since 8.0.0

**List of activated apps:** News, files, documents, images, contacts, calendar

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'oc260b8ba1a0',
  'passwordsalt' => 'ba272cb26e6c2dc8b40ba04e6805ef',
  'trusted_domains' => 
  array (
    0 => 'marlemion.mooo.com',
  ),
  'overwrite.cli.url' => '/owncloud',
  'datadirectory' => '/var/www/localhost/htdocs/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_root',
  'dbpassword' => 'XXXXXXXXXXXXXXX',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => 'XXXXXXXXXXXXXX',
  'loglevel' => 0,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...

bind mounts on usb drive

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:** Firefox 37

**Operating system:**

Arch linux 3.9 and Windows 7

### Logs
#### Web server error log

[Thu Apr 02 16:46:29.738896 2015] [:error] [pid 8703:tid 2798646320] [client XXXXX:55691] PHP Fatal error:  Call to a member function getId() on null in /var/www/localhost/htdocs/owncloud/apps/mail/lib/controller/accountscontroller.php on line 174, referer: http://XXXXXXX/owncloud/index.php/apps/mail/

#### ownCloud log (data/owncloud.log)

{"reqId":"d81df3decb5ef5608f9b0835bcae85e0","remoteAddr":"XXXX","app":"mail","message":"setting up auto detected account","level":1,"time":"2015-04-03T06:23:46+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"d81df3decb5ef5608f9b0835bcae85e0","remoteAddr":"XXXX","app":"mail","message":"Test-Account-Successful: eger, imap.googlemail.com, 993, wilhelm.eger@gmail.com, ssl","level":1,"time":"2015-04-03T06:23:48+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"d81df3decb5ef5608f9b0835bcae85e0","remoteAddr":"XXXX","app":"PHP","message":"Call to a member function getId() on string at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/controller\/accountscontroller.php#174","level":3,"time":"2015-04-03T06:23:49+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}

**Comment by marlemion** [comment]
I have tried the fix and the error message in the logs is gone, but still not luck:

{"reqId":"39e357e0d5126afb3e7ebe37e8402d55","remoteAddr":"xxxxx","app":"mail","message":"setting up auto detected account","level":1,"time":"2015-04-10T11:35:29+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"39e357e0d5126afb3e7ebe37e8402d55","remoteAddr":"xxxxx","app":"mail","message":"Test-Account-Successful: xxxx, imap.googlemail.com, 993, xxxx@googlemail.com, ssl","level":1,"time":"2015-04-10T11:35:36+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"39e357e0d5126afb3e7ebe37e8402d55","remoteAddr":"xxxxx","app":"mail","message":"account created 12","level":0,"time":"2015-04-10T11:35:37+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"10eb6dd25cc24c8dfe0d2e85b3477671","remoteAddr":"xxxxx","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4206): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1659): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1687): Horde_Imap_Client_Socket->_status(Array, 1)\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/mailbox.php(125): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/mailbox.php(129): OCA\\\\Mail\\\\Mailbox->getStatus(1)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(270): OCA\\\\Mail\\\\Mailbox->getTotalMessages()\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(301): OCA\\\\Mail\\\\Account->guessBestMailBox(Array)\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(188): OCA\\\\Mail\\\\Account->getSpecialFolder('drafts', true)\\n#9 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(335): OCA\\\\Mail\\\\Account->getSpecialFoldersIds(false)\\n#10 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(135): OCA\\\\Mail\\\\Account->localizeSpecialMailboxes()\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(147): OCA\\\\Mail\\\\Account->getMailboxes()\\n#12 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(57): OCA\\\\Mail\\\\Account->getListArray()\\n#13 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#14 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#16 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#17 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#21 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4488}","level":4,"time":"2015-04-10T11:35:40+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/12\/folders"}
{"reqId":"8a315769c5b677467a621836c17b08fe","remoteAddr":"xxxxx","app":"mail","message":"Setting up manually configured account","level":1,"time":"2015-04-10T11:38:40+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"8a315769c5b677467a621836c17b08fe","remoteAddr":"xxxxx","app":"mail","message":"Connecting to imap","level":0,"time":"2015-04-10T11:38:40+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"8a315769c5b677467a621836c17b08fe","remoteAddr":"xxxxx","app":"mail","message":"Connecting to smtp","level":0,"time":"2015-04-10T11:38:41+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"8a315769c5b677467a621836c17b08fe","remoteAddr":"xxxxx","app":"mail","message":"account created 13","level":0,"time":"2015-04-10T11:38:42+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"71ddff4393527b82dbcb354cf69f455f","remoteAddr":"xxxxx","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4206): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1659): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1687): Horde_Imap_Client_Socket->_status(Array, 1)\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/mailbox.php(125): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/mailbox.php(129): OCA\\\\Mail\\\\Mailbox->getStatus(1)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(270): OCA\\\\Mail\\\\Mailbox->getTotalMessages()\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(301): OCA\\\\Mail\\\\Account->guessBestMailBox(Array)\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(188): OCA\\\\Mail\\\\Account->getSpecialFolder('drafts', true)\\n#9 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(335): OCA\\\\Mail\\\\Account->getSpecialFoldersIds(false)\\n#10 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(135): OCA\\\\Mail\\\\Account->localizeSpecialMailboxes()\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(147): OCA\\\\Mail\\\\Account->getMailboxes()\\n#12 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(57): OCA\\\\Mail\\\\Account->getListArray()\\n#13 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#14 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#16 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#17 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#21 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4488}","level":4,"time":"2015-04-10T11:38:45+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/13\/folders"}

**Comment by jancborchardt** [comment]
@wurstchristoph you also have a Gmail account, right? Can you reproduce this?

**Comment by DeepDiver1975** [comment]
I just setup my gmail account once again. Works right away.

**Comment by wurstchristoph** [comment]
I does NOT work for me either:
```
{"reqId":"3970a76527afd0073654bf48bd64c322","remoteAddr":"::1","app":"mail","message":"setting up auto detected account","level":1,"time":"2015-04-11T07:03:27+00:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts"}
{"reqId":"3970a76527afd0073654bf48bd64c322","remoteAddr":"::1","app":"mail","message":"Test-Account-Successful: user, imap.googlemail.com, 993, *****@gmail.com, ssl","level":1,"time":"2015-04-11T07:03:28+00:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts"}
{"reqId":"3970a76527afd0073654bf48bd64c322","remoteAddr":"::1","app":"mail","message":"account created 2","level":0,"time":"2015-04-11T07:03:29+00:00","method":"POST","url":"\/index.php\/apps\/mail\/accounts"}
{"reqId":"4fdf452aa6171dff7ddd0ccb892d79cd","remoteAddr":"::1","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 ******\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4206): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 ******\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 ******\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1659): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 ******\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1687): Horde_Imap_Client_Socket->_status(Array, 1)\\n#4 ******\\\/apps\\\/mail\\\/lib\\\/mailbox.php(125): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\\n#5 ******\\\/apps\\\/mail\\\/lib\\\/mailbox.php(129): OCA\\\\Mail\\\\Mailbox->getStatus(1)\\n#6 ******\\\/apps\\\/mail\\\/lib\\\/account.php(270): OCA\\\\Mail\\\\Mailbox->getTotalMessages()\\n#7 ******\\\/apps\\\/mail\\\/lib\\\/account.php(301): OCA\\\\Mail\\\\Account->guessBestMailBox(Array)\\n#8 ******\\\/apps\\\/mail\\\/lib\\\/account.php(188): OCA\\\\Mail\\\\Account->getSpecialFolder('drafts', true)\\n#9 ******\\\/apps\\\/mail\\\/lib\\\/account.php(335): OCA\\\\Mail\\\\Account->getSpecialFoldersIds(false)\\n#10 ******\\\/apps\\\/mail\\\/lib\\\/account.php(135): OCA\\\\Mail\\\\Account->localizeSpecialMailboxes()\\n#11 ******\\\/apps\\\/mail\\\/lib\\\/account.php(147): OCA\\\\Mail\\\\Account->getMailboxes()\\n#12 ******\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(57): OCA\\\\Mail\\\\Account->getListArray()\\n#13 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#14 ******\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#15 ******\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#16 ******\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#17 ******\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#19 ******\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#20 ******\\\/lib\\\/base.php(782): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#21 ******\\\/index.php(36): OC::handleRequest()\\n#22 {main}\",\"File\":\"******\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4488}","level":4,"time":"2015-04-11T07:03:32+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/2\/folders"}
```

My Google account has 2-step verification enabled, so I used an app specific password for setting up my account. Could this be the reason?
@DeepDiver1975 do you have [less secure apps](https://www.google.com/settings/security/lesssecureapps) enabled?

**Comment by marlemion** [comment]
I've got this enabled, but it does not work either.

Just retried from scratch: removed the mail folder and cleaned the datase with the SQL commands provided in the Readme. Cloned again, got the composer parts, set the right permissions - same error.

**Comment by jancborchardt** [comment]
@marlemion do you also have 2-factor authentication enabled, as @wurstchristoph? Maybe that’s the reason.

**Comment by marlemion** [comment]
@jancborchardt AFAIK not. I use one password to login and no additional step.

**Comment by wurstchristoph** [comment]
@marlemion you can check it at https://myaccount.google.com at **Signing in**

**Comment by marlemion** [comment]
@wurstchristoph Thanks. It is NOT enabled.

**Comment by jancborchardt** [comment]
I just tested with a Gmail account and it immediately works.

Sorry @marlemion but no idea. Can you connect to any other account?

**Comment by jancborchardt** [comment]
@Henni didn’t you have a similar problem? Do you maybe have more info?

**Comment by marlemion** [comment]
Just tested this with a web.de account: works great.

**Comment by marlemion** [comment]
tested this with a completely new gmail account. imap activated, less secure apps allowed - same issue.

**Comment by jancborchardt** [comment]
@DeepDiver1975 aren’t we running unit tests against a completely new Gmail account, and everythign works? Any idea? :\

**Comment by Xenopathic** [comment]
I'm getting this problem too... other providers work, but Gmail throws a '"IMAP error reported by server" back. Tried both with autoconfig and manual setup.

**Comment by jancborchardt** [comment]
@Xenopathic @wurstchristoph can you maybe look further into this? @DeepDiver1975 and I can’t reproduce it.

**Comment by Xenopathic** [comment]
Hehe, now even Jenkins can reproduce this issue. https://travis-ci.org/owncloud/mail/jobs/59157318

**Comment by Xenopathic** [comment]
Done some debugging:

```
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: 5 STATUS INBOX MESSAGES
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: * STATUS "INBOX" (MESSAGES 3753)
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: 5 OK Success
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: 6 STATUS INBOX MESSAGES
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: * STATUS "INBOX" (MESSAGES 3753)
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: 6 OK Success
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: 7 STATUS [Gmail]/Sent Mail MESSAGES
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: 7 BAD Could not parse command
Apr 20 15:06:51 zeus.lan.mccorkell.me.uk ownCloud[28533]: IMAP error reported by server.
```

So far I can confirm the problem definitely isn't the space (at least, it isn't with Dovecot on my server)

**Comment by Xenopathic** [comment]
I think I've just found what's going wrong, this is what I see in a Wireshark trace (proxied through tcpserver and openssl s_client to open up the SSL tunnel):

```
Request: 6 STATUS INBOX (MESSAGES)
Response: * STATUS "INBOX" (MESSAGES 3754)
Request: 7 STATUS "[Gmail]/Sent Mail""" (MESSAGES)
Response: 7 BAD Could not parse command
```

Notice the triple quotation marks after 'Sent Mail'. I'm investigating what it could be, but it seems to be quite certainly a Horde IMAP issue.

PS: If anyone wants to do a similar thing, you'll need `tcpserver` from the package `ucspi-tcp`, then you'll need to run `tcpserver 127.0.0.1 50993 openssl s_client -connect imap.gmail.com:993 -quiet`. Create an email account with the IMAP server set to `127.0.0.1:50993`, then start up Wireshark. You'll need to manually enable the IMAP decoding on the traffic though - the port throws it off a bit.

**Comment by clementhk** [comment]
Looks like a terrible mistake by Horde.
You always need to think of escape when communicating.
This is from my own IMAP implementation, feel free to make use of it.

```
	private function escape($str, $force = false)
	{
		if(!strlen($str)) {
			return '""';
		}

		if(!$force && strpos($str, ' ') !== false) {
			$force = true;
		}

		$newstr = addcslashes($str, '"\\');
		return (!$force && ($str == $newstr))
			? $str : '"' . $newstr . '"';
	}

	private function unescape($str)
	{
		if($str[0] == '"' && substr($str, -1) == '"') {
			$str = substr($str, 1, -1);
			return strtr($str, ['\\"' => '"', '\\\\' => "\\"]);
		} else {
			return $str;
		}
	}
```

**Comment by Xenopathic** [comment]
I wish it were that simple. Horde quotes the strings it needs to, but just seems to put extra quotes on the end (which Gmail doesn't like). Their code is awkward to work with though, since it uses streams, not strings, *everywhere*.

**Comment by clementhk** [comment]
It could also be that owncloud mail is storing a wrongly unescaped folder name.

**Comment by clementhk** [comment]
(`"[Gmail]/Sent Mail"""` => `[Gmail]/Sent Mail"` after IMAP unescaping)

**Comment by Xenopathic** [comment]
Nope, that definitely isn't it. The Horde quoting filter (Horde_Imap_Client_Data_Format_Filter_Quote) seems to be the culprit. Before the filter is executed, I see `[Gmail]/Sent Mail` - after, I see `"[Gmail]/Sent Mail"""`

**Comment by wurstchristoph** [comment]
The quotation mark problem occurs also at #468

**Comment by Xenopathic** [comment]
@wurstchristoph THX

@jancborchardt  Ha, the problem manifests itself in multiple ways!

**Comment by clementhk** [comment]
Looks like the same problem as #468 then since it has a space in the folder name.

**Comment by Xenopathic** [comment]
Well the problem is in `Horde_Imap_Client_Data_Format_Filter_Quote`, if anyone wants a go at debugging it :smile:

**Comment by clementhk** [comment]
@Xenopathic it is fixed is master https://github.com/horde/horde/commit/ae1adf9f1549f6bb826b541274949cfd0e77457e .

**Comment by clementhk** [comment]
```
www:~ clement$ php new.php
"[Gmail]/Sent Mail"
www:~ clement$ 
www:~ clement$ 
www:~ clement$ php old.php
"[Gmail]/Sent Mail"""
www:~ clement$ 
www:~ clement$ 
www:~ clement$ php -v
PHP 5.4.37 (cli) (built: Jan 24 2015 20:45:26) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

Confirmed.

**Comment by Xenopathic** [comment]
@clementhk :clap: :trophy: :smile: 

It works!

**Comment by marlemion** [comment]
Thanks for your hard work, but I am afraid that this fix does not solve my problem.

What I did: git pull in the mail folder, readded account, behavior as befoer: account gets added, but does not show up, throws imap error. The account does also not show up in the list of accounts (bottom left)

{"reqId":"9bb7eb5a877f18a24d332f6be7709124","remoteAddr":"80.137.114.39","app":"mail","message":"Setting up manually configured account","level":1,"time":"2015-04-21T06:35:29+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"9bb7eb5a877f18a24d332f6be7709124","remoteAddr":"80.137.114.39","app":"mail","message":"Connecting to imap","level":0,"time":"2015-04-21T06:35:29+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"9bb7eb5a877f18a24d332f6be7709124","remoteAddr":"80.137.114.39","app":"mail","message":"Connecting to smtp","level":0,"time":"2015-04-21T06:35:29+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"9bb7eb5a877f18a24d332f6be7709124","remoteAddr":"80.137.114.39","app":"mail","message":"account created 4","level":0,"time":"2015-04-21T06:35:30+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"1a72f809e429badad4ca96d797b9813b","remoteAddr":"80.137.114.39","app":"mail","message":"loading messages 0 to 20 of folder <INBOX>","level":0,"time":"2015-04-21T06:35:33+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/folders\/SU5CT1g=\/messages"}
{"reqId":"6a7146857bb6fa433d95d33226e0104e","remoteAddr":"80.137.114.39","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4206): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1659): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1687): Horde_Imap_Client_Socket->_status(Array, 1)\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/mailbox.php(134): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/mailbox.php(138): OCA\\\\Mail\\\\Mailbox->getStatus(1)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(298): OCA\\\\Mail\\\\Mailbox->getTotalMessages()\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(329): OCA\\\\Mail\\\\Account->guessBestMailBox(Array)\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(216): OCA\\\\Mail\\\\Account->getSpecialFolder('drafts', true)\\n#9 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(363): OCA\\\\Mail\\\\Account->getSpecialFoldersIds(false)\\n#10 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(163): OCA\\\\Mail\\\\Account->localizeSpecialMailboxes()\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(175): OCA\\\\Mail\\\\Account->getMailboxes()\\n#12 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(63): OCA\\\\Mail\\\\Account->getListArray()\\n#13 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#14 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#16 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#17 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#21 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4488}","level":4,"time":"2015-04-21T06:35:35+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/4\/folders"}
{"reqId":"a43d2da221710e3739339c681d0e0333","remoteAddr":"80.137.114.39","app":"index","message":"Exception: {\"Message\":\"IMAP error reported by server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4206): Horde_Imap_Client_Socket->_getLine(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(4136): Horde_Imap_Client_Socket->_sendCmdChunk(Object(Horde_Imap_Client_Interaction_Pipeline), Array)\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php(1659): Horde_Imap_Client_Socket->_sendCmd(Object(Horde_Imap_Client_Interaction_Pipeline))\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(1687): Horde_Imap_Client_Socket->_status(Array, 1)\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/mailbox.php(134): Horde_Imap_Client_Base->status(Object(Horde_Imap_Client_Mailbox), 1)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/mailbox.php(138): OCA\\\\Mail\\\\Mailbox->getStatus(1)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(298): OCA\\\\Mail\\\\Mailbox->getTotalMessages()\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(329): OCA\\\\Mail\\\\Account->guessBestMailBox(Array)\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(216): OCA\\\\Mail\\\\Account->getSpecialFolder('drafts', true)\\n#9 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(363): OCA\\\\Mail\\\\Account->getSpecialFoldersIds(false)\\n#10 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(163): OCA\\\\Mail\\\\Account->localizeSpecialMailboxes()\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(175): OCA\\\\Mail\\\\Account->getMailboxes()\\n#12 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/folderscontroller.php(63): OCA\\\\Mail\\\\Account->getListArray()\\n#13 [internal function]: OCA\\\\Mail\\\\Controller\\\\FoldersController->index()\\n#14 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#16 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\FoldersController), 'index')\\n#17 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('FoldersControll...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#21 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":4488}","level":4,"time":"2015-04-21T06:35:38+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/4\/folders"}

**Comment by clementhk** [comment]
@marlemion have you updated your composer packages?

**Comment by marlemion** [comment]
No I didn't. :) But now I did. The error message above is gone, the account appears in the list (left bottom), but only the other accounts are displayed and browsable. The gmail account is still invisible. Maybe I need to reset the database?

{"reqId":"68605d9d6822a73f83c42a3fafb88700","remoteAddr":"80.137.114.39","app":"mail","message":"Setting up manually configured account","level":1,"time":"2015-04-21T07:15:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"68605d9d6822a73f83c42a3fafb88700","remoteAddr":"80.137.114.39","app":"mail","message":"Connecting to imap","level":0,"time":"2015-04-21T07:15:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"68605d9d6822a73f83c42a3fafb88700","remoteAddr":"80.137.114.39","app":"mail","message":"Connecting to smtp","level":0,"time":"2015-04-21T07:15:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"68605d9d6822a73f83c42a3fafb88700","remoteAddr":"80.137.114.39","app":"mail","message":"account created 6","level":0,"time":"2015-04-21T07:15:36+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"5b83efa31e93dccff03b1772e5930951","remoteAddr":"80.137.114.39","app":"mail","message":"loading messages 0 to 20 of folder <INBOX>","level":0,"time":"2015-04-21T07:15:37+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/folders\/SU5CT1g=\/messages"}
{"reqId":"ea84ee29436c6a06a3c2271ebbdd32da","remoteAddr":"80.137.114.39","app":"PHP","message":"Call to a member function getFolderId() on null at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php#217","level":3,"time":"2015-04-21T07:15:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/6\/folders"}
{"reqId":"520e723c1aeab47764d952ad0e0fa00f","remoteAddr":"80.137.114.39","app":"PHP","message":"Call to a member function getFolderId() on null at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php#217","level":3,"time":"2015-04-21T07:15:41+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/6\/folders"}

**Comment by clementhk** [comment]
I don't use owncloud mail (yet), just happened to see this issue from subscribing to this repo, so I don't have knowledge if you need to reset or not :)

But from a very quick look, 

https://github.com/owncloud/mail/blob/master/lib/account.php#L328

```
if ($guessBest === true && count($specialFolders) > 0) {
```

should be changed to 

```
if ($guessBest === true && count($specialFolders) > 1) {
```

Doing this could prevent calling `guessBestMailBox()` in most case, and I can't find in doc if returning int is nullable in `$folder->getTotalMessages()` -> `\Horde_Imap_Client::STATUS_MESSAGES)`, therefore I'd write it as `if ($bestGuess === null || $folder->getTotalMessages() > $maxMessages) {` in https://github.com/owncloud/mail/blob/master/lib/account.php#L298 .

But again, I'm not so sure about your issue as I'm not using owncloud mail yet.

**Comment by jancborchardt** [comment]
@clementhk well it’s very easy to install, just try it out. ;)

**Comment by marlemion** [comment]
That fixed it indeed! Thanks a lot! :) Confirmed.

**Comment by clementhk** [comment]
@marlemion which one?

**Comment by marlemion** [comment]
Ah, sorry. I have changed

if ($guessBest === true && count($specialFolders) > 0) {

to

if ($guessBest === true && count($specialFolders) > 1) {

in lib/accounts.php

**Comment by clementhk** [comment]
@marlemion mind to help to revert this and print out `$folder->getTotalMessages()` in https://github.com/owncloud/mail/blob/master/lib/account.php#L297 ?
Just so we could fix another issue.

**Comment by marlemion** [comment]
I will do it, but today is no time. Tomorrow. :)

**Comment by marlemion** [comment]
Well I added 'echo $folder->getTotalMessages():' and 'print $folder->getTotalMessages():', respectively, before the if statement. However, it does not print anything to the log:

{"reqId":"8f36e1a4e6d6d638a1ae09317827e5cb","remoteAddr":"80.137.117.187","app":"mail","message":"loading messages 0 to 20 of folder <INBOX>","level":0,"time":"2015-04-23T06:35:43+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/folders\/SU5CT1g=\/messages"}
{"reqId":"f07f980459b99a5078b649ddfceebdea","remoteAddr":"80.137.117.187","app":"mail","message":"Setting up manually configured account","level":1,"time":"2015-04-23T06:36:27+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"f07f980459b99a5078b649ddfceebdea","remoteAddr":"80.137.117.187","app":"mail","message":"Connecting to imap","level":0,"time":"2015-04-23T06:36:27+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"f07f980459b99a5078b649ddfceebdea","remoteAddr":"80.137.117.187","app":"mail","message":"Connecting to smtp","level":0,"time":"2015-04-23T06:36:28+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"f07f980459b99a5078b649ddfceebdea","remoteAddr":"80.137.117.187","app":"mail","message":"account created 9","level":0,"time":"2015-04-23T06:36:29+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"4de98ba93e879f0895cabe3552522c19","remoteAddr":"80.137.117.187","app":"mail","message":"loading messages 0 to 20 of folder <INBOX>","level":0,"time":"2015-04-23T06:36:31+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/folders\/SU5CT1g=\/messages"}
{"reqId":"a922bca922fcd368bda39e358cf3b2d6","remoteAddr":"80.137.117.187","app":"PHP","message":"Call to a member function getFolderId() on null at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php#217","level":3,"time":"2015-04-23T06:36:35+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/9\/folders"}
{"reqId":"e4c6c3e62c39db2cf238d4ea78135f3a","remoteAddr":"80.137.117.187","app":"PHP","message":"Call to a member function getFolderId() on null at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php#217","level":3,"time":"2015-04-23T06:36:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/9\/folders"}

**Comment by Xenopathic** [comment]
`echo` will try to print to the server output, which is the response sent back to the client. This will only break things like the HTML layout or even JSON responses. You need to use `\OC::$server->getLogger()->log(...)`

**Comment by marlemion** [comment]
Thanks.

Now I get:

{"reqId":"a76e62d04943e55d943d3c05f4fc01e5","remoteAddr":"80.137.118.18","app":"mail","message":"Setting up manually configured account","level":1,"time":"2015-04-24T06:39:33+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"a76e62d04943e55d943d3c05f4fc01e5","remoteAddr":"80.137.118.18","app":"mail","message":"Connecting to imap","level":0,"time":"2015-04-24T06:39:33+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"a76e62d04943e55d943d3c05f4fc01e5","remoteAddr":"80.137.118.18","app":"mail","message":"Connecting to smtp","level":0,"time":"2015-04-24T06:39:34+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"a76e62d04943e55d943d3c05f4fc01e5","remoteAddr":"80.137.118.18","app":"mail","message":"account created 10","level":0,"time":"2015-04-24T06:39:35+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/mail\/accounts"}
{"reqId":"dec49c0ed205e8492a3b0ea24fbee69c","remoteAddr":"80.137.118.18","app":"no app in context","message":"","level":5638,"time":"2015-04-24T06:39:37+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"dec49c0ed205e8492a3b0ea24fbee69c","remoteAddr":"80.137.118.18","app":"no app in context","message":"","level":6006,"time":"2015-04-24T06:39:38+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"dec49c0ed205e8492a3b0ea24fbee69c","remoteAddr":"80.137.118.18","app":"no app in context","message":"","level":1,"time":"2015-04-24T06:39:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"dec49c0ed205e8492a3b0ea24fbee69c","remoteAddr":"80.137.118.18","app":"no app in context","message":"","level":null,"time":"2015-04-24T06:39:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"dec49c0ed205e8492a3b0ea24fbee69c","remoteAddr":"80.137.118.18","app":"PHP","message":"Call to a member function getFolderId() on null at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php#217","level":3,"time":"2015-04-24T06:39:39+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"1247681755ab8563632372cbe67e9c4f","remoteAddr":"80.137.118.18","app":"no app in context","message":"","level":5638,"time":"2015-04-24T06:39:42+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"1247681755ab8563632372cbe67e9c4f","remoteAddr":"80.137.118.18","app":"no app in context","message":"","level":6006,"time":"2015-04-24T06:39:42+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"1247681755ab8563632372cbe67e9c4f","remoteAddr":"80.137.118.18","app":"no app in context","message":"","level":1,"time":"2015-04-24T06:39:43+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"1247681755ab8563632372cbe67e9c4f","remoteAddr":"80.137.118.18","app":"no app in context","message":"","level":null,"time":"2015-04-24T06:39:43+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"1247681755ab8563632372cbe67e9c4f","remoteAddr":"80.137.118.18","app":"PHP","message":"Call to a member function getFolderId() on null at \/var\/www\/localhost\/htdocs\/owncloud\/apps\/mail\/lib\/account.php#217","level":3,"time":"2015-04-24T06:39:44+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/10\/folders"}
{"reqId":"2ddd26837e01c7a325df383c180f49fb","remoteAddr":"80.137.118.18","app":"index","message":"Exception: {\"Message\":\"Mail server denied authentication.\",\"Code\":102,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Base.php(831): Horde_Imap_Client_Socket->_login()\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(84): Horde_Imap_Client_Base->login()\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/account.php(144): OCA\\\\Mail\\\\Account->getImapConnection()\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/messagescontroller.php(273): OCA\\\\Mail\\\\Account->getMailbox('INBOX')\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/lib\\\/controller\\\/messagescontroller.php(87): OCA\\\\Mail\\\\Controller\\\\MessagesController->getFolder()\\n#5 [internal function]: OCA\\\\Mail\\\\Controller\\\\MessagesController->index(0, 20, NULL)\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(158): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(86): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'index')\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(97): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Mail\\\\Controller\\\\MessagesController), 'index')\\n#9 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(44): OC\\\\AppFramework\\\\App::main('MessagesControl...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(250): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/lib\\\/base.php(767): OC\\\\Route\\\\Router->match('\\\/apps\\\/mail\\\/acco...')\\n#13 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/mail\\\/vendor\\\/pear-pear.horde.org\\\/Horde_Imap_Client\\\/Horde\\\/Imap\\\/Client\\\/Socket.php\",\"Line\":546}","level":4,"time":"2015-04-24T06:39:48+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/mail\/accounts\/1\/folders\/SU5CT1g=\/messages"}

**Comment by Xenopathic** [comment]
Looks like `getTotalMessages()` is returning nothing (or null), at least that's what I gather from those logs. Quick question though, are the `Mail server denied authentication` messages unrelated?

**Comment by clementhk** [comment]
@Xenopathic I think `Mail server denied authentication` is what happened if you don't apply https://github.com/owncloud/mail/issues/444#issuecomment-94699763

**Comment by clementhk** [comment]
So I'm right that `getTotalMessages()` could be `null`...
Anyone wants to send a proper pull request of https://github.com/owncloud/mail/issues/444#issuecomment-94699763 ?

**Comment by Xenopathic** [comment]
Yes, seems like the best course of action is to put the `$bestGuess === null` check in when checking for `getTotalMessages()`

**Comment by wurstchristoph** [comment]
My gmail account works now, the issue seems to be resolved.
